---
title: "Effectiveness of a malaria elimination campaign"
subtitle: "Cross-software reproducibility check"
output:
 tufte::tufte_html: default
 tufte::tufte_handout:
   citation_package: natbib
   latex_engine: xelatex
 tufte::tufte_book:
   citation_package: natbib
   latex_engine: xelatex
bibliography: bibliography.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, 
               echo = TRUE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```


```{r}
source('master.R')
```

```{r, message = FALSE, results = 'hide'}
# Get packages
library(Synth)

# Prepare data
gen_dummy <- function(condition){ifelse(condition, 1, ifelse(!condition, 0, NA))}

model_data <- 
  df %>%
  filter(age_group == '0-4') %>%
  filter(disease == 'MALARIA',
         district != 'XAI-XAI CITY',
         district != 'MANHICA',
         district != 'MASSINGIR') 

# Get a standardized time variable
model_data <-
  model_data %>%
  mutate(time = as.Date(paste0(year, '-01-01')) + (week*7)) %>%
  mutate(time = as.numeric(time)) %>%
  mutate(high_season = ifelse(month %in% 1:3, 1, 0))

# Generate a oct-dec lag
high_season <- model_data %>%
  filter(high_season == 1) %>%
  group_by(district, year) %>%
  summarise(cases = mean(pk)) %>%
  ungroup %>%
  group_by(district) %>%
  mutate(cases_lag = dplyr::lag(cases, n = 1, default = NA)) %>%
  ungroup %>%
  dplyr::select(-cases)
model_data <-
  left_join(model_data,
            high_season)
# Get 1 week lags too
model_data <-
  model_data %>%
  arrange(date) %>%
  group_by(district) %>%
  mutate(cases_lag1 = dplyr::lag(pk, n = 1, default = NA),
         cases_lag2 = dplyr::lag(pk, n = 2, default = NA))

# Filter away some stuff
model_data <- 
  model_data %>%
  filter(week < 52) %>%
  filter(date >= '2013-10-01')

# Get data with dummies
model_formula <- lm(pk ~  high_season + year + time, data = model_data)
model_matrix <- data.frame(model.matrix(model_formula)) %>%
  dplyr::select(-`X.Intercept.`) %>%
  mutate(pk = model_data$pk,
         district = model_data$district,
         itn_coverage = model_data$itn_coverage) %>%
  mutate(district_name = district) %>%
  mutate(district = as.numeric(factor(district)),
         cases_lag = model_data$cases_lag,
         cases_lag1 = model_data$cases_lag1,
         cases_lag2 = model_data$cases_lag2)

left <- 
  expand.grid(district = sort(unique(model_matrix$district)),
              time = sort(unique(model_matrix$time)))
right <- 
  model_matrix %>%
  group_by(district, time) %>%
  tally
balanced <- left_join(left, right)
model_matrix <-
  left_join(left, model_matrix)

# Fill the NAs
model_matrix <-
  model_matrix %>%
  arrange(time) %>%
  group_by(district) %>%
  mutate(high_season = zoo::na.locf(high_season), 
         year = zoo::na.locf(year),
         pk = zoo::na.locf(pk),
         itn_coverage = zoo::na.locf(itn_coverage),
         district_name = zoo::na.locf(district_name))

model_matrix <- data.frame(model_matrix)
  
prior_time <- sort(unique(model_matrix$time))
prior_time <- prior_time[prior_time <= as.numeric(as.Date('2015-08-01'))]
prepared_data <- 
  Synth::dataprep(foo = model_matrix,
                  predictors = c('itn_coverage',
                                 'cases_lag',
                                 'cases_lag1',
                                 'cases_lag2'),
                  predictors.op = 'mean',
                  dependent = 'pk',
                  time.variable = 'time',
                  unit.variable = 'district',
                  treatment.identifier = which(sort(unique(model_data$district)) == 'MAGUDE'),
                  controls.identifier = which(sort(unique(model_data$district)) != 'MAGUDE'),
                  unit.names.variable = 'district_name',
                  time.predictors.prior = prior_time,
                  time.optimize.ssr = prior_time,
                  time.plot = sort(unique(model_matrix$time)))

out <- Synth::synth(data.prep.obj = prepared_data)
# synth_tab <- synth.tab(synth.res = out,
#           dataprep.res = prepared_data,
#           round.digit = 3)
# # Predictor weights
# out$solution.v
# # Unit weights
# out$solution.w
```

# Unit weights

```{r}
uw <- left_join(
  model_matrix %>%
    filter(!duplicated(district)) %>%
    dplyr::select(district, district_name),
  data.frame(out$solution.w) %>%
    mutate(district = as.numeric(row.names(.)))
)
uw
ggplot(data = uw,
       aes(x = district_name,
           y = w.weight)) +
  geom_bar(stat = 'identity',
           alpha = 0.6,
           fill = 'darkorange') +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = 'District',
       y = 'Weight',
       title = 'Weights by district') +
  ggthemes::theme_hc()
```


# Comparison plot

(Difference between synthetic and observed)

```{r}
path.plot(synth.res = out,
          dataprep.res = prepared_data)
abline(v = as.numeric(as.Date('2015-10-01')), col = 'red')
```


# Gaps plot

(Same as above, but showing the gap between synthetic and real, rather than the actual values)

```{r}
gaps.plot(synth.res = out,
          dataprep.res = prepared_data)
abline(v = as.numeric(as.Date('2015-10-01')), col = 'red')
```
